"""Add slot model

Revision ID: 8659ffc85273
Revises: 21f0ec82a1d8
Create Date: 2024-11-26 18:09:54.538832

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8659ffc85273"
down_revision: Union[str, None] = "21f0ec82a1d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("time_range", postgresql.TSTZRANGE(), nullable=False),
        sa.Column("remaining_capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "start_time", "end_time", name="unique_slot"),
    )
    op.create_index("idx_slots_time_range", "slots", ["time_range"], unique=False, postgresql_using="gist")
    op.create_index(op.f("ix_slots_id"), "slots", ["id"], unique=False)
    op.create_table(
        "reservation_slots",
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["slots.id"],
        ),
        sa.PrimaryKeyConstraint("reservation_id", "slot_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservation_slots")
    op.drop_index(op.f("ix_slots_id"), table_name="slots")
    op.drop_index("idx_slots_time_range", table_name="slots", postgresql_using="gist")
    op.drop_table("slots")
    # ### end Alembic commands ###
