services:
  db:
    image: postgres:15.1
    container_name: grep_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: grep_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grep_db
    volumes:
      - grep_volume:/var/lib/postgresql/data

volumes:
  grep_volume:
